// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  TypedMap,
  Entity,
  Value,
  ValueKind,
  store,
  Address,
  Bytes,
  BigInt,
  BigDecimal
} from "@graphprotocol/graph-ts";

export class Collection extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Collection entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Collection entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Collection", id.toString(), this);
  }

  static load(id: string): Collection | null {
    return store.get("Collection", id) as Collection | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get items(): Array<string> | null {
    let value = this.get("items");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set items(value: Array<string> | null) {
    if (value === null) {
      this.unset("items");
    } else {
      this.set("items", Value.fromStringArray(value as Array<string>));
    }
  }

  get owner(): string {
    let value = this.get("owner");
    return value.toString();
  }

  set owner(value: string) {
    this.set("owner", Value.fromString(value));
  }

  get creator(): string {
    let value = this.get("creator");
    return value.toString();
  }

  set creator(value: string) {
    this.set("creator", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get symbol(): string {
    let value = this.get("symbol");
    return value.toString();
  }

  set symbol(value: string) {
    this.set("symbol", Value.fromString(value));
  }

  get isCompleted(): boolean {
    let value = this.get("isCompleted");
    return value.toBoolean();
  }

  set isCompleted(value: boolean) {
    this.set("isCompleted", Value.fromBoolean(value));
  }

  get isApproved(): boolean {
    let value = this.get("isApproved");
    return value.toBoolean();
  }

  set isApproved(value: boolean) {
    this.set("isApproved", Value.fromBoolean(value));
  }

  get isEditable(): boolean {
    let value = this.get("isEditable");
    return value.toBoolean();
  }

  set isEditable(value: boolean) {
    this.set("isEditable", Value.fromBoolean(value));
  }

  get minters(): Array<string> | null {
    let value = this.get("minters");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set minters(value: Array<string> | null) {
    if (value === null) {
      this.unset("minters");
    } else {
      this.set("minters", Value.fromStringArray(value as Array<string>));
    }
  }

  get managers(): Array<string> | null {
    let value = this.get("managers");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set managers(value: Array<string> | null) {
    if (value === null) {
      this.unset("managers");
    } else {
      this.set("managers", Value.fromStringArray(value as Array<string>));
    }
  }

  get urn(): string {
    let value = this.get("urn");
    return value.toString();
  }

  set urn(value: string) {
    this.set("urn", Value.fromString(value));
  }

  get itemsCount(): i32 {
    let value = this.get("itemsCount");
    return value.toI32();
  }

  set itemsCount(value: i32) {
    this.set("itemsCount", Value.fromI32(value));
  }

  get createdAt(): BigInt {
    let value = this.get("createdAt");
    return value.toBigInt();
  }

  set createdAt(value: BigInt) {
    this.set("createdAt", Value.fromBigInt(value));
  }

  get updatedAt(): BigInt {
    let value = this.get("updatedAt");
    return value.toBigInt();
  }

  set updatedAt(value: BigInt) {
    this.set("updatedAt", Value.fromBigInt(value));
  }

  get reviewedAt(): BigInt {
    let value = this.get("reviewedAt");
    return value.toBigInt();
  }

  set reviewedAt(value: BigInt) {
    this.set("reviewedAt", Value.fromBigInt(value));
  }

  get searchIsStoreMinter(): boolean {
    let value = this.get("searchIsStoreMinter");
    return value.toBoolean();
  }

  set searchIsStoreMinter(value: boolean) {
    this.set("searchIsStoreMinter", Value.fromBoolean(value));
  }

  get searchText(): string {
    let value = this.get("searchText");
    return value.toString();
  }

  set searchText(value: string) {
    this.set("searchText", Value.fromString(value));
  }
}

export class Item extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Item entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Item entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Item", id.toString(), this);
  }

  static load(id: string): Item | null {
    return store.get("Item", id) as Item | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get collection(): string {
    let value = this.get("collection");
    return value.toString();
  }

  set collection(value: string) {
    this.set("collection", Value.fromString(value));
  }

  get blockchainId(): BigInt {
    let value = this.get("blockchainId");
    return value.toBigInt();
  }

  set blockchainId(value: BigInt) {
    this.set("blockchainId", Value.fromBigInt(value));
  }

  get creator(): string {
    let value = this.get("creator");
    return value.toString();
  }

  set creator(value: string) {
    this.set("creator", Value.fromString(value));
  }

  get itemType(): string {
    let value = this.get("itemType");
    return value.toString();
  }

  set itemType(value: string) {
    this.set("itemType", Value.fromString(value));
  }

  get totalSupply(): BigInt {
    let value = this.get("totalSupply");
    return value.toBigInt();
  }

  set totalSupply(value: BigInt) {
    this.set("totalSupply", Value.fromBigInt(value));
  }

  get maxSupply(): BigInt {
    let value = this.get("maxSupply");
    return value.toBigInt();
  }

  set maxSupply(value: BigInt) {
    this.set("maxSupply", Value.fromBigInt(value));
  }

  get rarity(): string {
    let value = this.get("rarity");
    return value.toString();
  }

  set rarity(value: string) {
    this.set("rarity", Value.fromString(value));
  }

  get creationFee(): BigInt {
    let value = this.get("creationFee");
    return value.toBigInt();
  }

  set creationFee(value: BigInt) {
    this.set("creationFee", Value.fromBigInt(value));
  }

  get available(): BigInt {
    let value = this.get("available");
    return value.toBigInt();
  }

  set available(value: BigInt) {
    this.set("available", Value.fromBigInt(value));
  }

  get price(): BigInt {
    let value = this.get("price");
    return value.toBigInt();
  }

  set price(value: BigInt) {
    this.set("price", Value.fromBigInt(value));
  }

  get beneficiary(): string {
    let value = this.get("beneficiary");
    return value.toString();
  }

  set beneficiary(value: string) {
    this.set("beneficiary", Value.fromString(value));
  }

  get contentHash(): string | null {
    let value = this.get("contentHash");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set contentHash(value: string | null) {
    if (value === null) {
      this.unset("contentHash");
    } else {
      this.set("contentHash", Value.fromString(value as string));
    }
  }

  get URI(): string {
    let value = this.get("URI");
    return value.toString();
  }

  set URI(value: string) {
    this.set("URI", Value.fromString(value));
  }

  get image(): string | null {
    let value = this.get("image");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set image(value: string | null) {
    if (value === null) {
      this.unset("image");
    } else {
      this.set("image", Value.fromString(value as string));
    }
  }

  get minters(): Array<string> | null {
    let value = this.get("minters");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set minters(value: Array<string> | null) {
    if (value === null) {
      this.unset("minters");
    } else {
      this.set("minters", Value.fromStringArray(value as Array<string>));
    }
  }

  get managers(): Array<string> | null {
    let value = this.get("managers");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set managers(value: Array<string> | null) {
    if (value === null) {
      this.unset("managers");
    } else {
      this.set("managers", Value.fromStringArray(value as Array<string>));
    }
  }

  get metadata(): string | null {
    let value = this.get("metadata");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set metadata(value: string | null) {
    if (value === null) {
      this.unset("metadata");
    } else {
      this.set("metadata", Value.fromString(value as string));
    }
  }

  get rawMetadata(): string {
    let value = this.get("rawMetadata");
    return value.toString();
  }

  set rawMetadata(value: string) {
    this.set("rawMetadata", Value.fromString(value));
  }

  get urn(): string {
    let value = this.get("urn");
    return value.toString();
  }

  set urn(value: string) {
    this.set("urn", Value.fromString(value));
  }

  get nfts(): Array<string> | null {
    let value = this.get("nfts");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set nfts(value: Array<string> | null) {
    if (value === null) {
      this.unset("nfts");
    } else {
      this.set("nfts", Value.fromStringArray(value as Array<string>));
    }
  }

  get createdAt(): BigInt {
    let value = this.get("createdAt");
    return value.toBigInt();
  }

  set createdAt(value: BigInt) {
    this.set("createdAt", Value.fromBigInt(value));
  }

  get updatedAt(): BigInt {
    let value = this.get("updatedAt");
    return value.toBigInt();
  }

  set updatedAt(value: BigInt) {
    this.set("updatedAt", Value.fromBigInt(value));
  }

  get reviewedAt(): BigInt {
    let value = this.get("reviewedAt");
    return value.toBigInt();
  }

  set reviewedAt(value: BigInt) {
    this.set("reviewedAt", Value.fromBigInt(value));
  }

  get soldAt(): BigInt | null {
    let value = this.get("soldAt");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set soldAt(value: BigInt | null) {
    if (value === null) {
      this.unset("soldAt");
    } else {
      this.set("soldAt", Value.fromBigInt(value as BigInt));
    }
  }

  get sales(): i32 {
    let value = this.get("sales");
    return value.toI32();
  }

  set sales(value: i32) {
    this.set("sales", Value.fromI32(value));
  }

  get volume(): BigInt {
    let value = this.get("volume");
    return value.toBigInt();
  }

  set volume(value: BigInt) {
    this.set("volume", Value.fromBigInt(value));
  }

  get searchText(): string | null {
    let value = this.get("searchText");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchText(value: string | null) {
    if (value === null) {
      this.unset("searchText");
    } else {
      this.set("searchText", Value.fromString(value as string));
    }
  }

  get searchItemType(): string | null {
    let value = this.get("searchItemType");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchItemType(value: string | null) {
    if (value === null) {
      this.unset("searchItemType");
    } else {
      this.set("searchItemType", Value.fromString(value as string));
    }
  }

  get searchIsCollectionApproved(): boolean {
    let value = this.get("searchIsCollectionApproved");
    return value.toBoolean();
  }

  set searchIsCollectionApproved(value: boolean) {
    this.set("searchIsCollectionApproved", Value.fromBoolean(value));
  }

  get searchIsStoreMinter(): boolean {
    let value = this.get("searchIsStoreMinter");
    return value.toBoolean();
  }

  set searchIsStoreMinter(value: boolean) {
    this.set("searchIsStoreMinter", Value.fromBoolean(value));
  }

  get searchIsWearableHead(): boolean {
    let value = this.get("searchIsWearableHead");
    return value.toBoolean();
  }

  set searchIsWearableHead(value: boolean) {
    this.set("searchIsWearableHead", Value.fromBoolean(value));
  }

  get searchIsWearableAccessory(): boolean {
    let value = this.get("searchIsWearableAccessory");
    return value.toBoolean();
  }

  set searchIsWearableAccessory(value: boolean) {
    this.set("searchIsWearableAccessory", Value.fromBoolean(value));
  }

  get searchWearableCategory(): string | null {
    let value = this.get("searchWearableCategory");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchWearableCategory(value: string | null) {
    if (value === null) {
      this.unset("searchWearableCategory");
    } else {
      this.set("searchWearableCategory", Value.fromString(value as string));
    }
  }

  get searchWearableRarity(): string | null {
    let value = this.get("searchWearableRarity");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchWearableRarity(value: string | null) {
    if (value === null) {
      this.unset("searchWearableRarity");
    } else {
      this.set("searchWearableRarity", Value.fromString(value as string));
    }
  }

  get searchWearableBodyShapes(): Array<string> | null {
    let value = this.get("searchWearableBodyShapes");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set searchWearableBodyShapes(value: Array<string> | null) {
    if (value === null) {
      this.unset("searchWearableBodyShapes");
    } else {
      this.set(
        "searchWearableBodyShapes",
        Value.fromStringArray(value as Array<string>)
      );
    }
  }

  get searchEmoteCategory(): string | null {
    let value = this.get("searchEmoteCategory");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchEmoteCategory(value: string | null) {
    if (value === null) {
      this.unset("searchEmoteCategory");
    } else {
      this.set("searchEmoteCategory", Value.fromString(value as string));
    }
  }

  get searchEmoteRarity(): string | null {
    let value = this.get("searchEmoteRarity");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchEmoteRarity(value: string | null) {
    if (value === null) {
      this.unset("searchEmoteRarity");
    } else {
      this.set("searchEmoteRarity", Value.fromString(value as string));
    }
  }

  get searchEmoteBodyShapes(): Array<string> | null {
    let value = this.get("searchEmoteBodyShapes");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set searchEmoteBodyShapes(value: Array<string> | null) {
    if (value === null) {
      this.unset("searchEmoteBodyShapes");
    } else {
      this.set(
        "searchEmoteBodyShapes",
        Value.fromStringArray(value as Array<string>)
      );
    }
  }
}

export class NFT extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save NFT entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save NFT entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("NFT", id.toString(), this);
  }

  static load(id: string): NFT | null {
    return store.get("NFT", id) as NFT | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get tokenId(): BigInt {
    let value = this.get("tokenId");
    return value.toBigInt();
  }

  set tokenId(value: BigInt) {
    this.set("tokenId", Value.fromBigInt(value));
  }

  get contractAddress(): string {
    let value = this.get("contractAddress");
    return value.toString();
  }

  set contractAddress(value: string) {
    this.set("contractAddress", Value.fromString(value));
  }

  get itemBlockchainId(): BigInt | null {
    let value = this.get("itemBlockchainId");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set itemBlockchainId(value: BigInt | null) {
    if (value === null) {
      this.unset("itemBlockchainId");
    } else {
      this.set("itemBlockchainId", Value.fromBigInt(value as BigInt));
    }
  }

  get issuedId(): BigInt | null {
    let value = this.get("issuedId");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set issuedId(value: BigInt | null) {
    if (value === null) {
      this.unset("issuedId");
    } else {
      this.set("issuedId", Value.fromBigInt(value as BigInt));
    }
  }

  get itemType(): string {
    let value = this.get("itemType");
    return value.toString();
  }

  set itemType(value: string) {
    this.set("itemType", Value.fromString(value));
  }

  get owner(): string {
    let value = this.get("owner");
    return value.toString();
  }

  set owner(value: string) {
    this.set("owner", Value.fromString(value));
  }

  get tokenURI(): string | null {
    let value = this.get("tokenURI");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set tokenURI(value: string | null) {
    if (value === null) {
      this.unset("tokenURI");
    } else {
      this.set("tokenURI", Value.fromString(value as string));
    }
  }

  get image(): string | null {
    let value = this.get("image");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set image(value: string | null) {
    if (value === null) {
      this.unset("image");
    } else {
      this.set("image", Value.fromString(value as string));
    }
  }

  get urn(): string {
    let value = this.get("urn");
    return value.toString();
  }

  set urn(value: string) {
    this.set("urn", Value.fromString(value));
  }

  get orders(): Array<string> | null {
    let value = this.get("orders");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set orders(value: Array<string> | null) {
    if (value === null) {
      this.unset("orders");
    } else {
      this.set("orders", Value.fromStringArray(value as Array<string>));
    }
  }

  get bids(): Array<string> | null {
    let value = this.get("bids");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set bids(value: Array<string> | null) {
    if (value === null) {
      this.unset("bids");
    } else {
      this.set("bids", Value.fromStringArray(value as Array<string>));
    }
  }

  get activeOrder(): string | null {
    let value = this.get("activeOrder");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set activeOrder(value: string | null) {
    if (value === null) {
      this.unset("activeOrder");
    } else {
      this.set("activeOrder", Value.fromString(value as string));
    }
  }

  get collection(): string {
    let value = this.get("collection");
    return value.toString();
  }

  set collection(value: string) {
    this.set("collection", Value.fromString(value));
  }

  get item(): string | null {
    let value = this.get("item");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set item(value: string | null) {
    if (value === null) {
      this.unset("item");
    } else {
      this.set("item", Value.fromString(value as string));
    }
  }

  get metadata(): string | null {
    let value = this.get("metadata");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set metadata(value: string | null) {
    if (value === null) {
      this.unset("metadata");
    } else {
      this.set("metadata", Value.fromString(value as string));
    }
  }

  get createdAt(): BigInt {
    let value = this.get("createdAt");
    return value.toBigInt();
  }

  set createdAt(value: BigInt) {
    this.set("createdAt", Value.fromBigInt(value));
  }

  get updatedAt(): BigInt {
    let value = this.get("updatedAt");
    return value.toBigInt();
  }

  set updatedAt(value: BigInt) {
    this.set("updatedAt", Value.fromBigInt(value));
  }

  get soldAt(): BigInt | null {
    let value = this.get("soldAt");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set soldAt(value: BigInt | null) {
    if (value === null) {
      this.unset("soldAt");
    } else {
      this.set("soldAt", Value.fromBigInt(value as BigInt));
    }
  }

  get sales(): i32 {
    let value = this.get("sales");
    return value.toI32();
  }

  set sales(value: i32) {
    this.set("sales", Value.fromI32(value));
  }

  get volume(): BigInt {
    let value = this.get("volume");
    return value.toBigInt();
  }

  set volume(value: BigInt) {
    this.set("volume", Value.fromBigInt(value));
  }

  get searchText(): string | null {
    let value = this.get("searchText");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchText(value: string | null) {
    if (value === null) {
      this.unset("searchText");
    } else {
      this.set("searchText", Value.fromString(value as string));
    }
  }

  get searchItemType(): string | null {
    let value = this.get("searchItemType");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchItemType(value: string | null) {
    if (value === null) {
      this.unset("searchItemType");
    } else {
      this.set("searchItemType", Value.fromString(value as string));
    }
  }

  get searchIsWearableHead(): boolean {
    let value = this.get("searchIsWearableHead");
    return value.toBoolean();
  }

  set searchIsWearableHead(value: boolean) {
    this.set("searchIsWearableHead", Value.fromBoolean(value));
  }

  get searchIsWearableAccessory(): boolean {
    let value = this.get("searchIsWearableAccessory");
    return value.toBoolean();
  }

  set searchIsWearableAccessory(value: boolean) {
    this.set("searchIsWearableAccessory", Value.fromBoolean(value));
  }

  get searchWearableCategory(): string | null {
    let value = this.get("searchWearableCategory");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchWearableCategory(value: string | null) {
    if (value === null) {
      this.unset("searchWearableCategory");
    } else {
      this.set("searchWearableCategory", Value.fromString(value as string));
    }
  }

  get searchWearableRarity(): string | null {
    let value = this.get("searchWearableRarity");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchWearableRarity(value: string | null) {
    if (value === null) {
      this.unset("searchWearableRarity");
    } else {
      this.set("searchWearableRarity", Value.fromString(value as string));
    }
  }

  get searchWearableBodyShapes(): Array<string> | null {
    let value = this.get("searchWearableBodyShapes");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set searchWearableBodyShapes(value: Array<string> | null) {
    if (value === null) {
      this.unset("searchWearableBodyShapes");
    } else {
      this.set(
        "searchWearableBodyShapes",
        Value.fromStringArray(value as Array<string>)
      );
    }
  }

  get searchEmoteCategory(): string | null {
    let value = this.get("searchEmoteCategory");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchEmoteCategory(value: string | null) {
    if (value === null) {
      this.unset("searchEmoteCategory");
    } else {
      this.set("searchEmoteCategory", Value.fromString(value as string));
    }
  }

  get searchEmoteRarity(): string | null {
    let value = this.get("searchEmoteRarity");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchEmoteRarity(value: string | null) {
    if (value === null) {
      this.unset("searchEmoteRarity");
    } else {
      this.set("searchEmoteRarity", Value.fromString(value as string));
    }
  }

  get searchEmoteBodyShapes(): Array<string> | null {
    let value = this.get("searchEmoteBodyShapes");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set searchEmoteBodyShapes(value: Array<string> | null) {
    if (value === null) {
      this.unset("searchEmoteBodyShapes");
    } else {
      this.set(
        "searchEmoteBodyShapes",
        Value.fromStringArray(value as Array<string>)
      );
    }
  }

  get searchOrderStatus(): string | null {
    let value = this.get("searchOrderStatus");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set searchOrderStatus(value: string | null) {
    if (value === null) {
      this.unset("searchOrderStatus");
    } else {
      this.set("searchOrderStatus", Value.fromString(value as string));
    }
  }

  get searchOrderPrice(): BigInt | null {
    let value = this.get("searchOrderPrice");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set searchOrderPrice(value: BigInt | null) {
    if (value === null) {
      this.unset("searchOrderPrice");
    } else {
      this.set("searchOrderPrice", Value.fromBigInt(value as BigInt));
    }
  }

  get searchOrderExpiresAt(): BigInt | null {
    let value = this.get("searchOrderExpiresAt");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set searchOrderExpiresAt(value: BigInt | null) {
    if (value === null) {
      this.unset("searchOrderExpiresAt");
    } else {
      this.set("searchOrderExpiresAt", Value.fromBigInt(value as BigInt));
    }
  }

  get searchOrderCreatedAt(): BigInt | null {
    let value = this.get("searchOrderCreatedAt");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set searchOrderCreatedAt(value: BigInt | null) {
    if (value === null) {
      this.unset("searchOrderCreatedAt");
    } else {
      this.set("searchOrderCreatedAt", Value.fromBigInt(value as BigInt));
    }
  }
}

export class Metadata extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Metadata entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Metadata entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Metadata", id.toString(), this);
  }

  static load(id: string): Metadata | null {
    return store.get("Metadata", id) as Metadata | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get itemType(): string {
    let value = this.get("itemType");
    return value.toString();
  }

  set itemType(value: string) {
    this.set("itemType", Value.fromString(value));
  }

  get wearable(): string | null {
    let value = this.get("wearable");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set wearable(value: string | null) {
    if (value === null) {
      this.unset("wearable");
    } else {
      this.set("wearable", Value.fromString(value as string));
    }
  }

  get emote(): string | null {
    let value = this.get("emote");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set emote(value: string | null) {
    if (value === null) {
      this.unset("emote");
    } else {
      this.set("emote", Value.fromString(value as string));
    }
  }
}

export class Wearable extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Wearable entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Wearable entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Wearable", id.toString(), this);
  }

  static load(id: string): Wearable | null {
    return store.get("Wearable", id) as Wearable | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get description(): string {
    let value = this.get("description");
    return value.toString();
  }

  set description(value: string) {
    this.set("description", Value.fromString(value));
  }

  get collection(): string {
    let value = this.get("collection");
    return value.toString();
  }

  set collection(value: string) {
    this.set("collection", Value.fromString(value));
  }

  get category(): string {
    let value = this.get("category");
    return value.toString();
  }

  set category(value: string) {
    this.set("category", Value.fromString(value));
  }

  get rarity(): string {
    let value = this.get("rarity");
    return value.toString();
  }

  set rarity(value: string) {
    this.set("rarity", Value.fromString(value));
  }

  get bodyShapes(): Array<string> | null {
    let value = this.get("bodyShapes");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set bodyShapes(value: Array<string> | null) {
    if (value === null) {
      this.unset("bodyShapes");
    } else {
      this.set("bodyShapes", Value.fromStringArray(value as Array<string>));
    }
  }
}

export class Emote extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Emote entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Emote entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Emote", id.toString(), this);
  }

  static load(id: string): Emote | null {
    return store.get("Emote", id) as Emote | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get description(): string {
    let value = this.get("description");
    return value.toString();
  }

  set description(value: string) {
    this.set("description", Value.fromString(value));
  }

  get collection(): string {
    let value = this.get("collection");
    return value.toString();
  }

  set collection(value: string) {
    this.set("collection", Value.fromString(value));
  }

  get category(): string {
    let value = this.get("category");
    return value.toString();
  }

  set category(value: string) {
    this.set("category", Value.fromString(value));
  }

  get rarity(): string {
    let value = this.get("rarity");
    return value.toString();
  }

  set rarity(value: string) {
    this.set("rarity", Value.fromString(value));
  }

  get bodyShapes(): Array<string> | null {
    let value = this.get("bodyShapes");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set bodyShapes(value: Array<string> | null) {
    if (value === null) {
      this.unset("bodyShapes");
    } else {
      this.set("bodyShapes", Value.fromStringArray(value as Array<string>));
    }
  }
}

export class Rarity extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Rarity entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Rarity entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Rarity", id.toString(), this);
  }

  static load(id: string): Rarity | null {
    return store.get("Rarity", id) as Rarity | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get maxSupply(): BigInt {
    let value = this.get("maxSupply");
    return value.toBigInt();
  }

  set maxSupply(value: BigInt) {
    this.set("maxSupply", Value.fromBigInt(value));
  }

  get price(): BigInt {
    let value = this.get("price");
    return value.toBigInt();
  }

  set price(value: BigInt) {
    this.set("price", Value.fromBigInt(value));
  }
}

export class Account extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Account entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Account entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Account", id.toString(), this);
  }

  static load(id: string): Account | null {
    return store.get("Account", id) as Account | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get address(): Bytes {
    let value = this.get("address");
    return value.toBytes();
  }

  set address(value: Bytes) {
    this.set("address", Value.fromBytes(value));
  }

  get nfts(): Array<string> | null {
    let value = this.get("nfts");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set nfts(value: Array<string> | null) {
    if (value === null) {
      this.unset("nfts");
    } else {
      this.set("nfts", Value.fromStringArray(value as Array<string>));
    }
  }

  get isCommitteeMember(): boolean {
    let value = this.get("isCommitteeMember");
    return value.toBoolean();
  }

  set isCommitteeMember(value: boolean) {
    this.set("isCommitteeMember", Value.fromBoolean(value));
  }

  get totalCurations(): i32 {
    let value = this.get("totalCurations");
    return value.toI32();
  }

  set totalCurations(value: i32) {
    this.set("totalCurations", Value.fromI32(value));
  }

  get sales(): i32 {
    let value = this.get("sales");
    return value.toI32();
  }

  set sales(value: i32) {
    this.set("sales", Value.fromI32(value));
  }

  get purchases(): i32 {
    let value = this.get("purchases");
    return value.toI32();
  }

  set purchases(value: i32) {
    this.set("purchases", Value.fromI32(value));
  }

  get spent(): BigInt {
    let value = this.get("spent");
    return value.toBigInt();
  }

  set spent(value: BigInt) {
    this.set("spent", Value.fromBigInt(value));
  }

  get earned(): BigInt {
    let value = this.get("earned");
    return value.toBigInt();
  }

  set earned(value: BigInt) {
    this.set("earned", Value.fromBigInt(value));
  }

  get royalties(): BigInt {
    let value = this.get("royalties");
    return value.toBigInt();
  }

  set royalties(value: BigInt) {
    this.set("royalties", Value.fromBigInt(value));
  }
}

export class Order extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Order entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Order entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Order", id.toString(), this);
  }

  static load(id: string): Order | null {
    return store.get("Order", id) as Order | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get marketplaceAddress(): Bytes {
    let value = this.get("marketplaceAddress");
    return value.toBytes();
  }

  set marketplaceAddress(value: Bytes) {
    this.set("marketplaceAddress", Value.fromBytes(value));
  }

  get nft(): string | null {
    let value = this.get("nft");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set nft(value: string | null) {
    if (value === null) {
      this.unset("nft");
    } else {
      this.set("nft", Value.fromString(value as string));
    }
  }

  get nftAddress(): Bytes {
    let value = this.get("nftAddress");
    return value.toBytes();
  }

  set nftAddress(value: Bytes) {
    this.set("nftAddress", Value.fromBytes(value));
  }

  get tokenId(): BigInt {
    let value = this.get("tokenId");
    return value.toBigInt();
  }

  set tokenId(value: BigInt) {
    this.set("tokenId", Value.fromBigInt(value));
  }

  get txHash(): Bytes {
    let value = this.get("txHash");
    return value.toBytes();
  }

  set txHash(value: Bytes) {
    this.set("txHash", Value.fromBytes(value));
  }

  get owner(): Bytes {
    let value = this.get("owner");
    return value.toBytes();
  }

  set owner(value: Bytes) {
    this.set("owner", Value.fromBytes(value));
  }

  get buyer(): Bytes | null {
    let value = this.get("buyer");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBytes();
    }
  }

  set buyer(value: Bytes | null) {
    if (value === null) {
      this.unset("buyer");
    } else {
      this.set("buyer", Value.fromBytes(value as Bytes));
    }
  }

  get price(): BigInt {
    let value = this.get("price");
    return value.toBigInt();
  }

  set price(value: BigInt) {
    this.set("price", Value.fromBigInt(value));
  }

  get status(): string {
    let value = this.get("status");
    return value.toString();
  }

  set status(value: string) {
    this.set("status", Value.fromString(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    return value.toBigInt();
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get expiresAt(): BigInt {
    let value = this.get("expiresAt");
    return value.toBigInt();
  }

  set expiresAt(value: BigInt) {
    this.set("expiresAt", Value.fromBigInt(value));
  }

  get createdAt(): BigInt {
    let value = this.get("createdAt");
    return value.toBigInt();
  }

  set createdAt(value: BigInt) {
    this.set("createdAt", Value.fromBigInt(value));
  }

  get updatedAt(): BigInt {
    let value = this.get("updatedAt");
    return value.toBigInt();
  }

  set updatedAt(value: BigInt) {
    this.set("updatedAt", Value.fromBigInt(value));
  }
}

export class Bid extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Bid entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Bid entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Bid", id.toString(), this);
  }

  static load(id: string): Bid | null {
    return store.get("Bid", id) as Bid | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get bidAddress(): Bytes {
    let value = this.get("bidAddress");
    return value.toBytes();
  }

  set bidAddress(value: Bytes) {
    this.set("bidAddress", Value.fromBytes(value));
  }

  get nft(): string | null {
    let value = this.get("nft");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set nft(value: string | null) {
    if (value === null) {
      this.unset("nft");
    } else {
      this.set("nft", Value.fromString(value as string));
    }
  }

  get nftAddress(): Bytes {
    let value = this.get("nftAddress");
    return value.toBytes();
  }

  set nftAddress(value: Bytes) {
    this.set("nftAddress", Value.fromBytes(value));
  }

  get tokenId(): BigInt {
    let value = this.get("tokenId");
    return value.toBigInt();
  }

  set tokenId(value: BigInt) {
    this.set("tokenId", Value.fromBigInt(value));
  }

  get blockchainId(): string {
    let value = this.get("blockchainId");
    return value.toString();
  }

  set blockchainId(value: string) {
    this.set("blockchainId", Value.fromString(value));
  }

  get bidder(): Bytes | null {
    let value = this.get("bidder");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBytes();
    }
  }

  set bidder(value: Bytes | null) {
    if (value === null) {
      this.unset("bidder");
    } else {
      this.set("bidder", Value.fromBytes(value as Bytes));
    }
  }

  get seller(): Bytes | null {
    let value = this.get("seller");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBytes();
    }
  }

  set seller(value: Bytes | null) {
    if (value === null) {
      this.unset("seller");
    } else {
      this.set("seller", Value.fromBytes(value as Bytes));
    }
  }

  get price(): BigInt {
    let value = this.get("price");
    return value.toBigInt();
  }

  set price(value: BigInt) {
    this.set("price", Value.fromBigInt(value));
  }

  get status(): string {
    let value = this.get("status");
    return value.toString();
  }

  set status(value: string) {
    this.set("status", Value.fromString(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    return value.toBigInt();
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get expiresAt(): BigInt {
    let value = this.get("expiresAt");
    return value.toBigInt();
  }

  set expiresAt(value: BigInt) {
    this.set("expiresAt", Value.fromBigInt(value));
  }

  get createdAt(): BigInt {
    let value = this.get("createdAt");
    return value.toBigInt();
  }

  set createdAt(value: BigInt) {
    this.set("createdAt", Value.fromBigInt(value));
  }

  get updatedAt(): BigInt {
    let value = this.get("updatedAt");
    return value.toBigInt();
  }

  set updatedAt(value: BigInt) {
    this.set("updatedAt", Value.fromBigInt(value));
  }
}

export class Count extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Count entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Count entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Count", id.toString(), this);
  }

  static load(id: string): Count | null {
    return store.get("Count", id) as Count | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get orderTotal(): i32 {
    let value = this.get("orderTotal");
    return value.toI32();
  }

  set orderTotal(value: i32) {
    this.set("orderTotal", Value.fromI32(value));
  }

  get bidTotal(): i32 {
    let value = this.get("bidTotal");
    return value.toI32();
  }

  set bidTotal(value: i32) {
    this.set("bidTotal", Value.fromI32(value));
  }

  get collectionTotal(): i32 {
    let value = this.get("collectionTotal");
    return value.toI32();
  }

  set collectionTotal(value: i32) {
    this.set("collectionTotal", Value.fromI32(value));
  }

  get itemTotal(): i32 {
    let value = this.get("itemTotal");
    return value.toI32();
  }

  set itemTotal(value: i32) {
    this.set("itemTotal", Value.fromI32(value));
  }

  get nftTotal(): i32 {
    let value = this.get("nftTotal");
    return value.toI32();
  }

  set nftTotal(value: i32) {
    this.set("nftTotal", Value.fromI32(value));
  }

  get salesTotal(): i32 {
    let value = this.get("salesTotal");
    return value.toI32();
  }

  set salesTotal(value: i32) {
    this.set("salesTotal", Value.fromI32(value));
  }

  get salesManaTotal(): BigInt {
    let value = this.get("salesManaTotal");
    return value.toBigInt();
  }

  set salesManaTotal(value: BigInt) {
    this.set("salesManaTotal", Value.fromBigInt(value));
  }

  get primarySalesTotal(): i32 {
    let value = this.get("primarySalesTotal");
    return value.toI32();
  }

  set primarySalesTotal(value: i32) {
    this.set("primarySalesTotal", Value.fromI32(value));
  }

  get primarySalesManaTotal(): BigInt {
    let value = this.get("primarySalesManaTotal");
    return value.toBigInt();
  }

  set primarySalesManaTotal(value: BigInt) {
    this.set("primarySalesManaTotal", Value.fromBigInt(value));
  }

  get secondarySalesTotal(): i32 {
    let value = this.get("secondarySalesTotal");
    return value.toI32();
  }

  set secondarySalesTotal(value: i32) {
    this.set("secondarySalesTotal", Value.fromI32(value));
  }

  get secondarySalesManaTotal(): BigInt {
    let value = this.get("secondarySalesManaTotal");
    return value.toBigInt();
  }

  set secondarySalesManaTotal(value: BigInt) {
    this.set("secondarySalesManaTotal", Value.fromBigInt(value));
  }

  get royaltiesManaTotal(): BigInt {
    let value = this.get("royaltiesManaTotal");
    return value.toBigInt();
  }

  set royaltiesManaTotal(value: BigInt) {
    this.set("royaltiesManaTotal", Value.fromBigInt(value));
  }

  get started(): i32 {
    let value = this.get("started");
    return value.toI32();
  }

  set started(value: i32) {
    this.set("started", Value.fromI32(value));
  }
}

export class Mint extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Mint entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Mint entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Mint", id.toString(), this);
  }

  static load(id: string): Mint | null {
    return store.get("Mint", id) as Mint | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get item(): string {
    let value = this.get("item");
    return value.toString();
  }

  set item(value: string) {
    this.set("item", Value.fromString(value));
  }

  get nft(): string {
    let value = this.get("nft");
    return value.toString();
  }

  set nft(value: string) {
    this.set("nft", Value.fromString(value));
  }

  get creator(): string {
    let value = this.get("creator");
    return value.toString();
  }

  set creator(value: string) {
    this.set("creator", Value.fromString(value));
  }

  get beneficiary(): string {
    let value = this.get("beneficiary");
    return value.toString();
  }

  set beneficiary(value: string) {
    this.set("beneficiary", Value.fromString(value));
  }

  get minter(): string {
    let value = this.get("minter");
    return value.toString();
  }

  set minter(value: string) {
    this.set("minter", Value.fromString(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get searchPrimarySalePrice(): BigInt | null {
    let value = this.get("searchPrimarySalePrice");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set searchPrimarySalePrice(value: BigInt | null) {
    if (value === null) {
      this.unset("searchPrimarySalePrice");
    } else {
      this.set("searchPrimarySalePrice", Value.fromBigInt(value as BigInt));
    }
  }

  get searchContractAddress(): string {
    let value = this.get("searchContractAddress");
    return value.toString();
  }

  set searchContractAddress(value: string) {
    this.set("searchContractAddress", Value.fromString(value));
  }

  get searchItemId(): BigInt {
    let value = this.get("searchItemId");
    return value.toBigInt();
  }

  set searchItemId(value: BigInt) {
    this.set("searchItemId", Value.fromBigInt(value));
  }

  get searchTokenId(): BigInt {
    let value = this.get("searchTokenId");
    return value.toBigInt();
  }

  set searchTokenId(value: BigInt) {
    this.set("searchTokenId", Value.fromBigInt(value));
  }

  get searchIssuedId(): BigInt | null {
    let value = this.get("searchIssuedId");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set searchIssuedId(value: BigInt | null) {
    if (value === null) {
      this.unset("searchIssuedId");
    } else {
      this.set("searchIssuedId", Value.fromBigInt(value as BigInt));
    }
  }

  get searchIsStoreMinter(): boolean {
    let value = this.get("searchIsStoreMinter");
    return value.toBoolean();
  }

  set searchIsStoreMinter(value: boolean) {
    this.set("searchIsStoreMinter", Value.fromBoolean(value));
  }
}

export class Curation extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Curation entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Curation entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Curation", id.toString(), this);
  }

  static load(id: string): Curation | null {
    return store.get("Curation", id) as Curation | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get txHash(): Bytes {
    let value = this.get("txHash");
    return value.toBytes();
  }

  set txHash(value: Bytes) {
    this.set("txHash", Value.fromBytes(value));
  }

  get curator(): string {
    let value = this.get("curator");
    return value.toString();
  }

  set curator(value: string) {
    this.set("curator", Value.fromString(value));
  }

  get collection(): string {
    let value = this.get("collection");
    return value.toString();
  }

  set collection(value: string) {
    this.set("collection", Value.fromString(value));
  }

  get item(): string | null {
    let value = this.get("item");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set item(value: string | null) {
    if (value === null) {
      this.unset("item");
    } else {
      this.set("item", Value.fromString(value as string));
    }
  }

  get isApproved(): boolean {
    let value = this.get("isApproved");
    return value.toBoolean();
  }

  set isApproved(value: boolean) {
    this.set("isApproved", Value.fromBoolean(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }
}

export class Sale extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Sale entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Sale entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Sale", id.toString(), this);
  }

  static load(id: string): Sale | null {
    return store.get("Sale", id) as Sale | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get type(): string {
    let value = this.get("type");
    return value.toString();
  }

  set type(value: string) {
    this.set("type", Value.fromString(value));
  }

  get buyer(): Bytes {
    let value = this.get("buyer");
    return value.toBytes();
  }

  set buyer(value: Bytes) {
    this.set("buyer", Value.fromBytes(value));
  }

  get seller(): Bytes {
    let value = this.get("seller");
    return value.toBytes();
  }

  set seller(value: Bytes) {
    this.set("seller", Value.fromBytes(value));
  }

  get price(): BigInt {
    let value = this.get("price");
    return value.toBigInt();
  }

  set price(value: BigInt) {
    this.set("price", Value.fromBigInt(value));
  }

  get feesCollectorCut(): BigInt {
    let value = this.get("feesCollectorCut");
    return value.toBigInt();
  }

  set feesCollectorCut(value: BigInt) {
    this.set("feesCollectorCut", Value.fromBigInt(value));
  }

  get feesCollector(): Bytes {
    let value = this.get("feesCollector");
    return value.toBytes();
  }

  set feesCollector(value: Bytes) {
    this.set("feesCollector", Value.fromBytes(value));
  }

  get royaltiesCut(): BigInt {
    let value = this.get("royaltiesCut");
    return value.toBigInt();
  }

  set royaltiesCut(value: BigInt) {
    this.set("royaltiesCut", Value.fromBigInt(value));
  }

  get royaltiesCollector(): Bytes {
    let value = this.get("royaltiesCollector");
    return value.toBytes();
  }

  set royaltiesCollector(value: Bytes) {
    this.set("royaltiesCollector", Value.fromBytes(value));
  }

  get item(): string {
    let value = this.get("item");
    return value.toString();
  }

  set item(value: string) {
    this.set("item", Value.fromString(value));
  }

  get nft(): string {
    let value = this.get("nft");
    return value.toString();
  }

  set nft(value: string) {
    this.set("nft", Value.fromString(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get txHash(): Bytes {
    let value = this.get("txHash");
    return value.toBytes();
  }

  set txHash(value: Bytes) {
    this.set("txHash", Value.fromBytes(value));
  }

  get searchTokenId(): BigInt {
    let value = this.get("searchTokenId");
    return value.toBigInt();
  }

  set searchTokenId(value: BigInt) {
    this.set("searchTokenId", Value.fromBigInt(value));
  }

  get searchItemId(): BigInt {
    let value = this.get("searchItemId");
    return value.toBigInt();
  }

  set searchItemId(value: BigInt) {
    this.set("searchItemId", Value.fromBigInt(value));
  }

  get searchContractAddress(): string {
    let value = this.get("searchContractAddress");
    return value.toString();
  }

  set searchContractAddress(value: string) {
    this.set("searchContractAddress", Value.fromString(value));
  }
}

export class VolumeDayData extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save VolumeDayData entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save VolumeDayData entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("VolumeDayData", id.toString(), this);
  }

  static load(id: string): VolumeDayData | null {
    return store.get("VolumeDayData", id) as VolumeDayData | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get date(): i32 {
    let value = this.get("date");
    return value.toI32();
  }

  set date(value: i32) {
    this.set("date", Value.fromI32(value));
  }

  get dailySales(): i32 {
    let value = this.get("dailySales");
    return value.toI32();
  }

  set dailySales(value: i32) {
    this.set("dailySales", Value.fromI32(value));
  }

  get dailyVolumeMANA(): BigInt {
    let value = this.get("dailyVolumeMANA");
    return value.toBigInt();
  }

  set dailyVolumeMANA(value: BigInt) {
    this.set("dailyVolumeMANA", Value.fromBigInt(value));
  }

  get dailyCreatorsEarnings(): BigInt {
    let value = this.get("dailyCreatorsEarnings");
    return value.toBigInt();
  }

  set dailyCreatorsEarnings(value: BigInt) {
    this.set("dailyCreatorsEarnings", Value.fromBigInt(value));
  }

  get dailyDAOEarnings(): BigInt {
    let value = this.get("dailyDAOEarnings");
    return value.toBigInt();
  }

  set dailyDAOEarnings(value: BigInt) {
    this.set("dailyDAOEarnings", Value.fromBigInt(value));
  }
}
