// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class BidAccepted extends ethereum.Event {
  get params(): BidAccepted__Params {
    return new BidAccepted__Params(this);
  }
}

export class BidAccepted__Params {
  _event: BidAccepted;

  constructor(event: BidAccepted) {
    this._event = event;
  }

  get _id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get _tokenAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get _tokenId(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get _bidder(): Address {
    return this._event.parameters[3].value.toAddress();
  }

  get _seller(): Address {
    return this._event.parameters[4].value.toAddress();
  }

  get _price(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }

  get _fee(): BigInt {
    return this._event.parameters[6].value.toBigInt();
  }
}

export class BidCancelled extends ethereum.Event {
  get params(): BidCancelled__Params {
    return new BidCancelled__Params(this);
  }
}

export class BidCancelled__Params {
  _event: BidCancelled;

  constructor(event: BidCancelled) {
    this._event = event;
  }

  get _id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get _tokenAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get _tokenId(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get _bidder(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class BidCreated extends ethereum.Event {
  get params(): BidCreated__Params {
    return new BidCreated__Params(this);
  }
}

export class BidCreated__Params {
  _event: BidCreated;

  constructor(event: BidCreated) {
    this._event = event;
  }

  get _id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get _tokenAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get _tokenId(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get _bidder(): Address {
    return this._event.parameters[3].value.toAddress();
  }

  get _price(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }

  get _expiresAt(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }

  get _fingerprint(): Bytes {
    return this._event.parameters[6].value.toBytes();
  }
}

export class ChangedFeesCollectorCutPerMillion extends ethereum.Event {
  get params(): ChangedFeesCollectorCutPerMillion__Params {
    return new ChangedFeesCollectorCutPerMillion__Params(this);
  }
}

export class ChangedFeesCollectorCutPerMillion__Params {
  _event: ChangedFeesCollectorCutPerMillion;

  constructor(event: ChangedFeesCollectorCutPerMillion) {
    this._event = event;
  }

  get _feesCollectorCutPerMillion(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }
}

export class ChangedRoyaltiesCutPerMillion extends ethereum.Event {
  get params(): ChangedRoyaltiesCutPerMillion__Params {
    return new ChangedRoyaltiesCutPerMillion__Params(this);
  }
}

export class ChangedRoyaltiesCutPerMillion__Params {
  _event: ChangedRoyaltiesCutPerMillion;

  constructor(event: ChangedRoyaltiesCutPerMillion) {
    this._event = event;
  }

  get _royaltiesCutPerMillion(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }
}

export class FeesCollectorSet extends ethereum.Event {
  get params(): FeesCollectorSet__Params {
    return new FeesCollectorSet__Params(this);
  }
}

export class FeesCollectorSet__Params {
  _event: FeesCollectorSet;

  constructor(event: FeesCollectorSet) {
    this._event = event;
  }

  get _oldFeesCollector(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get _newFeesCollector(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class MetaTransactionExecuted extends ethereum.Event {
  get params(): MetaTransactionExecuted__Params {
    return new MetaTransactionExecuted__Params(this);
  }
}

export class MetaTransactionExecuted__Params {
  _event: MetaTransactionExecuted;

  constructor(event: MetaTransactionExecuted) {
    this._event = event;
  }

  get userAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get relayerAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get functionSignature(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class Paused extends ethereum.Event {
  get params(): Paused__Params {
    return new Paused__Params(this);
  }
}

export class Paused__Params {
  _event: Paused;

  constructor(event: Paused) {
    this._event = event;
  }

  get account(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class RoyaltiesManagerSet extends ethereum.Event {
  get params(): RoyaltiesManagerSet__Params {
    return new RoyaltiesManagerSet__Params(this);
  }
}

export class RoyaltiesManagerSet__Params {
  _event: RoyaltiesManagerSet;

  constructor(event: RoyaltiesManagerSet) {
    this._event = event;
  }

  get _oldRoyaltiesManager(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get _newRoyaltiesManager(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class Unpaused extends ethereum.Event {
  get params(): Unpaused__Params {
    return new Unpaused__Params(this);
  }
}

export class Unpaused__Params {
  _event: Unpaused;

  constructor(event: Unpaused) {
    this._event = event;
  }

  get account(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class ERC721BidV2__getBidByBidderResult {
  value0: BigInt;
  value1: Bytes;
  value2: Address;
  value3: BigInt;
  value4: BigInt;

  constructor(
    value0: BigInt,
    value1: Bytes,
    value2: Address,
    value3: BigInt,
    value4: BigInt
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromFixedBytes(this.value1));
    map.set("value2", ethereum.Value.fromAddress(this.value2));
    map.set("value3", ethereum.Value.fromUnsignedBigInt(this.value3));
    map.set("value4", ethereum.Value.fromUnsignedBigInt(this.value4));
    return map;
  }
}

export class ERC721BidV2__getBidByTokenResult {
  value0: Bytes;
  value1: Address;
  value2: BigInt;
  value3: BigInt;

  constructor(value0: Bytes, value1: Address, value2: BigInt, value3: BigInt) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromFixedBytes(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    map.set("value2", ethereum.Value.fromUnsignedBigInt(this.value2));
    map.set("value3", ethereum.Value.fromUnsignedBigInt(this.value3));
    return map;
  }
}

export class ERC721BidV2 extends ethereum.SmartContract {
  static bind(address: Address): ERC721BidV2 {
    return new ERC721BidV2("ERC721BidV2", address);
  }

  ERC721Composable_ValidateFingerprint(): Bytes {
    let result = super.call(
      "ERC721Composable_ValidateFingerprint",
      "ERC721Composable_ValidateFingerprint():(bytes4)",
      []
    );

    return result[0].toBytes();
  }

  try_ERC721Composable_ValidateFingerprint(): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "ERC721Composable_ValidateFingerprint",
      "ERC721Composable_ValidateFingerprint():(bytes4)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  ERC721_Interface(): Bytes {
    let result = super.call(
      "ERC721_Interface",
      "ERC721_Interface():(bytes4)",
      []
    );

    return result[0].toBytes();
  }

  try_ERC721_Interface(): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "ERC721_Interface",
      "ERC721_Interface():(bytes4)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  ERC721_Received(): Bytes {
    let result = super.call(
      "ERC721_Received",
      "ERC721_Received():(bytes4)",
      []
    );

    return result[0].toBytes();
  }

  try_ERC721_Received(): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "ERC721_Received",
      "ERC721_Received():(bytes4)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  MAX_BID_DURATION(): BigInt {
    let result = super.call(
      "MAX_BID_DURATION",
      "MAX_BID_DURATION():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try_MAX_BID_DURATION(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "MAX_BID_DURATION",
      "MAX_BID_DURATION():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  MIN_BID_DURATION(): BigInt {
    let result = super.call(
      "MIN_BID_DURATION",
      "MIN_BID_DURATION():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try_MIN_BID_DURATION(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "MIN_BID_DURATION",
      "MIN_BID_DURATION():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  ONE_MILLION(): BigInt {
    let result = super.call("ONE_MILLION", "ONE_MILLION():(uint256)", []);

    return result[0].toBigInt();
  }

  try_ONE_MILLION(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("ONE_MILLION", "ONE_MILLION():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  bidCounterByToken(param0: Address, param1: BigInt): BigInt {
    let result = super.call(
      "bidCounterByToken",
      "bidCounterByToken(address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromUnsignedBigInt(param1)
      ]
    );

    return result[0].toBigInt();
  }

  try_bidCounterByToken(
    param0: Address,
    param1: BigInt
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "bidCounterByToken",
      "bidCounterByToken(address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromUnsignedBigInt(param1)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  bidIdByTokenAndBidder(
    param0: Address,
    param1: BigInt,
    param2: Address
  ): Bytes {
    let result = super.call(
      "bidIdByTokenAndBidder",
      "bidIdByTokenAndBidder(address,uint256,address):(bytes32)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromUnsignedBigInt(param1),
        ethereum.Value.fromAddress(param2)
      ]
    );

    return result[0].toBytes();
  }

  try_bidIdByTokenAndBidder(
    param0: Address,
    param1: BigInt,
    param2: Address
  ): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "bidIdByTokenAndBidder",
      "bidIdByTokenAndBidder(address,uint256,address):(bytes32)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromUnsignedBigInt(param1),
        ethereum.Value.fromAddress(param2)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  bidIndexByBidId(param0: Bytes): BigInt {
    let result = super.call(
      "bidIndexByBidId",
      "bidIndexByBidId(bytes32):(uint256)",
      [ethereum.Value.fromFixedBytes(param0)]
    );

    return result[0].toBigInt();
  }

  try_bidIndexByBidId(param0: Bytes): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "bidIndexByBidId",
      "bidIndexByBidId(bytes32):(uint256)",
      [ethereum.Value.fromFixedBytes(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  domainSeparator(): Bytes {
    let result = super.call(
      "domainSeparator",
      "domainSeparator():(bytes32)",
      []
    );

    return result[0].toBytes();
  }

  try_domainSeparator(): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "domainSeparator",
      "domainSeparator():(bytes32)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  feesCollector(): Address {
    let result = super.call("feesCollector", "feesCollector():(address)", []);

    return result[0].toAddress();
  }

  try_feesCollector(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "feesCollector",
      "feesCollector():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  feesCollectorCutPerMillion(): BigInt {
    let result = super.call(
      "feesCollectorCutPerMillion",
      "feesCollectorCutPerMillion():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try_feesCollectorCutPerMillion(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "feesCollectorCutPerMillion",
      "feesCollectorCutPerMillion():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getBidByBidder(
    _tokenAddress: Address,
    _tokenId: BigInt,
    _bidder: Address
  ): ERC721BidV2__getBidByBidderResult {
    let result = super.call(
      "getBidByBidder",
      "getBidByBidder(address,uint256,address):(uint256,bytes32,address,uint256,uint256)",
      [
        ethereum.Value.fromAddress(_tokenAddress),
        ethereum.Value.fromUnsignedBigInt(_tokenId),
        ethereum.Value.fromAddress(_bidder)
      ]
    );

    return new ERC721BidV2__getBidByBidderResult(
      result[0].toBigInt(),
      result[1].toBytes(),
      result[2].toAddress(),
      result[3].toBigInt(),
      result[4].toBigInt()
    );
  }

  try_getBidByBidder(
    _tokenAddress: Address,
    _tokenId: BigInt,
    _bidder: Address
  ): ethereum.CallResult<ERC721BidV2__getBidByBidderResult> {
    let result = super.tryCall(
      "getBidByBidder",
      "getBidByBidder(address,uint256,address):(uint256,bytes32,address,uint256,uint256)",
      [
        ethereum.Value.fromAddress(_tokenAddress),
        ethereum.Value.fromUnsignedBigInt(_tokenId),
        ethereum.Value.fromAddress(_bidder)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new ERC721BidV2__getBidByBidderResult(
        value[0].toBigInt(),
        value[1].toBytes(),
        value[2].toAddress(),
        value[3].toBigInt(),
        value[4].toBigInt()
      )
    );
  }

  getBidByToken(
    _tokenAddress: Address,
    _tokenId: BigInt,
    _index: BigInt
  ): ERC721BidV2__getBidByTokenResult {
    let result = super.call(
      "getBidByToken",
      "getBidByToken(address,uint256,uint256):(bytes32,address,uint256,uint256)",
      [
        ethereum.Value.fromAddress(_tokenAddress),
        ethereum.Value.fromUnsignedBigInt(_tokenId),
        ethereum.Value.fromUnsignedBigInt(_index)
      ]
    );

    return new ERC721BidV2__getBidByTokenResult(
      result[0].toBytes(),
      result[1].toAddress(),
      result[2].toBigInt(),
      result[3].toBigInt()
    );
  }

  try_getBidByToken(
    _tokenAddress: Address,
    _tokenId: BigInt,
    _index: BigInt
  ): ethereum.CallResult<ERC721BidV2__getBidByTokenResult> {
    let result = super.tryCall(
      "getBidByToken",
      "getBidByToken(address,uint256,uint256):(bytes32,address,uint256,uint256)",
      [
        ethereum.Value.fromAddress(_tokenAddress),
        ethereum.Value.fromUnsignedBigInt(_tokenId),
        ethereum.Value.fromUnsignedBigInt(_index)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new ERC721BidV2__getBidByTokenResult(
        value[0].toBytes(),
        value[1].toAddress(),
        value[2].toBigInt(),
        value[3].toBigInt()
      )
    );
  }

  getChainId(): BigInt {
    let result = super.call("getChainId", "getChainId():(uint256)", []);

    return result[0].toBigInt();
  }

  try_getChainId(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("getChainId", "getChainId():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getNonce(user: Address): BigInt {
    let result = super.call("getNonce", "getNonce(address):(uint256)", [
      ethereum.Value.fromAddress(user)
    ]);

    return result[0].toBigInt();
  }

  try_getNonce(user: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall("getNonce", "getNonce(address):(uint256)", [
      ethereum.Value.fromAddress(user)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  manaToken(): Address {
    let result = super.call("manaToken", "manaToken():(address)", []);

    return result[0].toAddress();
  }

  try_manaToken(): ethereum.CallResult<Address> {
    let result = super.tryCall("manaToken", "manaToken():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  onERC721Received(
    _from: Address,
    param1: Address,
    _tokenId: BigInt,
    _data: Bytes
  ): Bytes {
    let result = super.call(
      "onERC721Received",
      "onERC721Received(address,address,uint256,bytes):(bytes4)",
      [
        ethereum.Value.fromAddress(_from),
        ethereum.Value.fromAddress(param1),
        ethereum.Value.fromUnsignedBigInt(_tokenId),
        ethereum.Value.fromBytes(_data)
      ]
    );

    return result[0].toBytes();
  }

  try_onERC721Received(
    _from: Address,
    param1: Address,
    _tokenId: BigInt,
    _data: Bytes
  ): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "onERC721Received",
      "onERC721Received(address,address,uint256,bytes):(bytes4)",
      [
        ethereum.Value.fromAddress(_from),
        ethereum.Value.fromAddress(param1),
        ethereum.Value.fromUnsignedBigInt(_tokenId),
        ethereum.Value.fromBytes(_data)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  owner(): Address {
    let result = super.call("owner", "owner():(address)", []);

    return result[0].toAddress();
  }

  try_owner(): ethereum.CallResult<Address> {
    let result = super.tryCall("owner", "owner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  paused(): boolean {
    let result = super.call("paused", "paused():(bool)", []);

    return result[0].toBoolean();
  }

  try_paused(): ethereum.CallResult<boolean> {
    let result = super.tryCall("paused", "paused():(bool)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  royaltiesCutPerMillion(): BigInt {
    let result = super.call(
      "royaltiesCutPerMillion",
      "royaltiesCutPerMillion():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try_royaltiesCutPerMillion(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "royaltiesCutPerMillion",
      "royaltiesCutPerMillion():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  royaltiesManager(): Address {
    let result = super.call(
      "royaltiesManager",
      "royaltiesManager():(address)",
      []
    );

    return result[0].toAddress();
  }

  try_royaltiesManager(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "royaltiesManager",
      "royaltiesManager():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _owner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _feesCollector(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _manaToken(): Address {
    return this._call.inputValues[2].value.toAddress();
  }

  get _royaltiesManager(): Address {
    return this._call.inputValues[3].value.toAddress();
  }

  get _feesCollectorCutPerMillion(): BigInt {
    return this._call.inputValues[4].value.toBigInt();
  }

  get _royaltiesCutPerMillion(): BigInt {
    return this._call.inputValues[5].value.toBigInt();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class CancelBidCall extends ethereum.Call {
  get inputs(): CancelBidCall__Inputs {
    return new CancelBidCall__Inputs(this);
  }

  get outputs(): CancelBidCall__Outputs {
    return new CancelBidCall__Outputs(this);
  }
}

export class CancelBidCall__Inputs {
  _call: CancelBidCall;

  constructor(call: CancelBidCall) {
    this._call = call;
  }

  get _tokenAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _tokenId(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class CancelBidCall__Outputs {
  _call: CancelBidCall;

  constructor(call: CancelBidCall) {
    this._call = call;
  }
}

export class ExecuteMetaTransactionCall extends ethereum.Call {
  get inputs(): ExecuteMetaTransactionCall__Inputs {
    return new ExecuteMetaTransactionCall__Inputs(this);
  }

  get outputs(): ExecuteMetaTransactionCall__Outputs {
    return new ExecuteMetaTransactionCall__Outputs(this);
  }
}

export class ExecuteMetaTransactionCall__Inputs {
  _call: ExecuteMetaTransactionCall;

  constructor(call: ExecuteMetaTransactionCall) {
    this._call = call;
  }

  get userAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get functionSignature(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }

  get sigR(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }

  get sigS(): Bytes {
    return this._call.inputValues[3].value.toBytes();
  }

  get sigV(): i32 {
    return this._call.inputValues[4].value.toI32();
  }
}

export class ExecuteMetaTransactionCall__Outputs {
  _call: ExecuteMetaTransactionCall;

  constructor(call: ExecuteMetaTransactionCall) {
    this._call = call;
  }

  get value0(): Bytes {
    return this._call.outputValues[0].value.toBytes();
  }
}

export class OnERC721ReceivedCall extends ethereum.Call {
  get inputs(): OnERC721ReceivedCall__Inputs {
    return new OnERC721ReceivedCall__Inputs(this);
  }

  get outputs(): OnERC721ReceivedCall__Outputs {
    return new OnERC721ReceivedCall__Outputs(this);
  }
}

export class OnERC721ReceivedCall__Inputs {
  _call: OnERC721ReceivedCall;

  constructor(call: OnERC721ReceivedCall) {
    this._call = call;
  }

  get _from(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get value1(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _tokenId(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }

  get _data(): Bytes {
    return this._call.inputValues[3].value.toBytes();
  }
}

export class OnERC721ReceivedCall__Outputs {
  _call: OnERC721ReceivedCall;

  constructor(call: OnERC721ReceivedCall) {
    this._call = call;
  }

  get value0(): Bytes {
    return this._call.outputValues[0].value.toBytes();
  }
}

export class PauseCall extends ethereum.Call {
  get inputs(): PauseCall__Inputs {
    return new PauseCall__Inputs(this);
  }

  get outputs(): PauseCall__Outputs {
    return new PauseCall__Outputs(this);
  }
}

export class PauseCall__Inputs {
  _call: PauseCall;

  constructor(call: PauseCall) {
    this._call = call;
  }
}

export class PauseCall__Outputs {
  _call: PauseCall;

  constructor(call: PauseCall) {
    this._call = call;
  }
}

export class PlaceBidCall extends ethereum.Call {
  get inputs(): PlaceBidCall__Inputs {
    return new PlaceBidCall__Inputs(this);
  }

  get outputs(): PlaceBidCall__Outputs {
    return new PlaceBidCall__Outputs(this);
  }
}

export class PlaceBidCall__Inputs {
  _call: PlaceBidCall;

  constructor(call: PlaceBidCall) {
    this._call = call;
  }

  get _tokenAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _tokenId(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get _price(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }

  get _duration(): BigInt {
    return this._call.inputValues[3].value.toBigInt();
  }
}

export class PlaceBidCall__Outputs {
  _call: PlaceBidCall;

  constructor(call: PlaceBidCall) {
    this._call = call;
  }
}

export class PlaceBid1Call extends ethereum.Call {
  get inputs(): PlaceBid1Call__Inputs {
    return new PlaceBid1Call__Inputs(this);
  }

  get outputs(): PlaceBid1Call__Outputs {
    return new PlaceBid1Call__Outputs(this);
  }
}

export class PlaceBid1Call__Inputs {
  _call: PlaceBid1Call;

  constructor(call: PlaceBid1Call) {
    this._call = call;
  }

  get _tokenAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _tokenId(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get _price(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }

  get _duration(): BigInt {
    return this._call.inputValues[3].value.toBigInt();
  }

  get _fingerprint(): Bytes {
    return this._call.inputValues[4].value.toBytes();
  }
}

export class PlaceBid1Call__Outputs {
  _call: PlaceBid1Call;

  constructor(call: PlaceBid1Call) {
    this._call = call;
  }
}

export class RemoveExpiredBidsCall extends ethereum.Call {
  get inputs(): RemoveExpiredBidsCall__Inputs {
    return new RemoveExpiredBidsCall__Inputs(this);
  }

  get outputs(): RemoveExpiredBidsCall__Outputs {
    return new RemoveExpiredBidsCall__Outputs(this);
  }
}

export class RemoveExpiredBidsCall__Inputs {
  _call: RemoveExpiredBidsCall;

  constructor(call: RemoveExpiredBidsCall) {
    this._call = call;
  }

  get _tokenAddresses(): Array<Address> {
    return this._call.inputValues[0].value.toAddressArray();
  }

  get _tokenIds(): Array<BigInt> {
    return this._call.inputValues[1].value.toBigIntArray();
  }

  get _bidders(): Array<Address> {
    return this._call.inputValues[2].value.toAddressArray();
  }
}

export class RemoveExpiredBidsCall__Outputs {
  _call: RemoveExpiredBidsCall;

  constructor(call: RemoveExpiredBidsCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall extends ethereum.Call {
  get inputs(): RenounceOwnershipCall__Inputs {
    return new RenounceOwnershipCall__Inputs(this);
  }

  get outputs(): RenounceOwnershipCall__Outputs {
    return new RenounceOwnershipCall__Outputs(this);
  }
}

export class RenounceOwnershipCall__Inputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall__Outputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class SetFeesCollectorCall extends ethereum.Call {
  get inputs(): SetFeesCollectorCall__Inputs {
    return new SetFeesCollectorCall__Inputs(this);
  }

  get outputs(): SetFeesCollectorCall__Outputs {
    return new SetFeesCollectorCall__Outputs(this);
  }
}

export class SetFeesCollectorCall__Inputs {
  _call: SetFeesCollectorCall;

  constructor(call: SetFeesCollectorCall) {
    this._call = call;
  }

  get _newFeesCollector(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetFeesCollectorCall__Outputs {
  _call: SetFeesCollectorCall;

  constructor(call: SetFeesCollectorCall) {
    this._call = call;
  }
}

export class SetFeesCollectorCutPerMillionCall extends ethereum.Call {
  get inputs(): SetFeesCollectorCutPerMillionCall__Inputs {
    return new SetFeesCollectorCutPerMillionCall__Inputs(this);
  }

  get outputs(): SetFeesCollectorCutPerMillionCall__Outputs {
    return new SetFeesCollectorCutPerMillionCall__Outputs(this);
  }
}

export class SetFeesCollectorCutPerMillionCall__Inputs {
  _call: SetFeesCollectorCutPerMillionCall;

  constructor(call: SetFeesCollectorCutPerMillionCall) {
    this._call = call;
  }

  get _feesCollectorCutPerMillion(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetFeesCollectorCutPerMillionCall__Outputs {
  _call: SetFeesCollectorCutPerMillionCall;

  constructor(call: SetFeesCollectorCutPerMillionCall) {
    this._call = call;
  }
}

export class SetRoyaltiesCutPerMillionCall extends ethereum.Call {
  get inputs(): SetRoyaltiesCutPerMillionCall__Inputs {
    return new SetRoyaltiesCutPerMillionCall__Inputs(this);
  }

  get outputs(): SetRoyaltiesCutPerMillionCall__Outputs {
    return new SetRoyaltiesCutPerMillionCall__Outputs(this);
  }
}

export class SetRoyaltiesCutPerMillionCall__Inputs {
  _call: SetRoyaltiesCutPerMillionCall;

  constructor(call: SetRoyaltiesCutPerMillionCall) {
    this._call = call;
  }

  get _royaltiesCutPerMillion(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetRoyaltiesCutPerMillionCall__Outputs {
  _call: SetRoyaltiesCutPerMillionCall;

  constructor(call: SetRoyaltiesCutPerMillionCall) {
    this._call = call;
  }
}

export class SetRoyaltiesManagerCall extends ethereum.Call {
  get inputs(): SetRoyaltiesManagerCall__Inputs {
    return new SetRoyaltiesManagerCall__Inputs(this);
  }

  get outputs(): SetRoyaltiesManagerCall__Outputs {
    return new SetRoyaltiesManagerCall__Outputs(this);
  }
}

export class SetRoyaltiesManagerCall__Inputs {
  _call: SetRoyaltiesManagerCall;

  constructor(call: SetRoyaltiesManagerCall) {
    this._call = call;
  }

  get _newRoyaltiesManager(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetRoyaltiesManagerCall__Outputs {
  _call: SetRoyaltiesManagerCall;

  constructor(call: SetRoyaltiesManagerCall) {
    this._call = call;
  }
}

export class TransferOwnershipCall extends ethereum.Call {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}
